# Conexão com o Banco de Dados (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-green-hall-ayc6v519-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SYL8QVs7Mnzj
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Nome da Aplicação e Porta
spring.application.name=barbersaas-api
server.port=8080